import React, {useState} from 'react';
import {View, Text, Image, TouchableOpacity} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import Icon1 from 'react-native-vector-icons/Feather';
// import {useNavigation} from '@react-navigation/native';
import LinearGradient from 'react-native-linear-gradient';

const onboardingData = [
  {
    id: '1',
    title: 'Smart Legal Practice Starts Here',
    description:
      'Save hours every week with intelligent case tracking, reminders, and updates—built for busy lawyers',
    image: require('../assets/one.png'),
  },
  {
    id: '2',
    title: 'Stay Ahead, Stay Informed',
    description:
      'Get instant access to cause lists, orders, and past judgements—organized and accessible in one tap',
    image: require('../assets/two.png'),
  },
  {
    id: '3',
    title: 'Seamless Client Communication',
    description:
      'Notify clients with full or summarized case proceedings via Email, WhatsApp, or PDF—auto-generated by AI',
    image: require('../assets/three.png'),
  },
  {
    id: '4',
    title: 'Your Digital Legal Assistant',
    description:
      'From reminders to drafting summaries, let our automation take care of the repetitive work so you can focus on winning cases',
    image: require('../assets/four.png'),
  },
];
const StartScreen = () => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const insets = useSafeAreaInsets();

  const handleNext = () => {
    if (currentIndex < onboardingData.length - 1) {
      setCurrentIndex(currentIndex + 1);
    }
  };

  const handleSkip = () => {
    setCurrentIndex(onboardingData.length - 1);
  };

  const item = onboardingData[currentIndex];

  return (
    <View className="flex-1 bg-[#062C35]" style={{paddingTop: insets.top}}>
      {/* Top Header */}
      <View className="flex-row justify-between items-center px-6 py-2 mt-2">
        {currentIndex > 0 ? (
          <TouchableOpacity
            onPress={() => setCurrentIndex(prev => Math.max(prev - 1, 0))}
            className="w-10 h-10 rounded-full border border-[#006261] justify-center items-center">
            <Icon1 name="arrow-left" size={18} color="#01B879" />
          </TouchableOpacity>
        ) : (
          <View />
        )}
        <Text className="text-white" onPress={handleSkip}>
          Skip
        </Text>
      </View>

      {/* Main Content */}
      <View className="flex-1 justify-center bottom-10 items-center px-6">
        <Image
          source={item.image}
          className="w-full h-70 "
          resizeMode="contain"
        />

        <Text className="text-white text-xl mt-20 font-bold text-center">
          {item.title}
        </Text>
        <Text className="text-gray-300 mt-2 text-center">
          {item.description}
        </Text>

        {/* Progress bar */}
      </View>

      {/* Bottom Button */}
      <View className="px-6 pb-6">
        <View className="px-6 pb-6">
          <View className="flex-row justify-center space-x-2">
            {onboardingData.map((_, index) => {
              if (index === currentIndex) {
                return (
                  <LinearGradient
                    key={index}
                    colors={['#006261', '#01B879']}
                    start={{x: 0, y: 0}}
                    end={{x: 1, y: 0}}
                    className="h-1 mb-10 rounded-full w-16"
                  />
                );
              } else {
                return (
                  <View
                    key={index}
                    className="h-1 mb-10 rounded-full bg-gray-600 w-16"
                  />
                );
              }
            })}
          </View>
        </View>
        <TouchableOpacity
          onPress={handleNext}
          className="rounded-xl overflow-hidden">
          <LinearGradient
            colors={['#006261', '#01B879']}
            start={{x: 0, y: 0}}
            end={{x: 1, y: 1}}
            className="py-3 rounded-xl">
            <Text className="text-center text-white font-semibold text-lg">
              {currentIndex === onboardingData.length - 1
                ? 'Get Started'
                : 'Next'}
            </Text>
          </LinearGradient>
        </TouchableOpacity>
      </View>
    </View>
  );
};

export default StartScreen;
